source 'https://rubygems.org'

gem 'capistrano', '~> 3.6'
gem 'capistrano-bower', '~> 1.1'
gem 'capistrano-npm', '~> 1.0', '>= 1.0.2'
gem 'sass', '~> 3.4', '>= 3.4.22'
gem 'net-ssh', '~> 3.1', '>= 3.1.1'
gem 'capistrano-rbenv', '~> 2.0', '>= 2.0.4'
gem 'capistrano-passenger', '~> 0.2.0'
gem 'capistrano-bundler', '~> 1.1', '>= 1.1.4'
gem 'capistrano-grunt'